# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: byGIS
email: me@komzpa.net
description: >- # this means to ignore newlines until "baseurl:"
  byGIS - Географические Информационные Системы в Беларуси
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: bygis

# Build settings
markdown: kramdown
#remote_theme: tocttou/hacker-blog
plugins:
  - jekyll-feed

author:
  name: "SomeHacker"
  email: "someone@somewebsite.somedomain"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
#permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
#      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "byGIS community"
year : "2017-2020"
